accounts/urls.py
from django.urls import path
from accounts.views import JoinView, AuthorsView, UserLoginView, UserLogoutView, ProfileView, ProfileUpdateView

from django.views.generic import RedirectView
# RedirectView will redirect url--> www.google.com/accounts/ to www.google.com/accounts/login/

app_name = 'accounts'
urlpatterns = [
    path('', RedirectView.as_view(url='login/', permanent=True)),
    path('join/', JoinView.as_view(), name='join'),
    path('authors/', AuthorsView.as_view(), name='authors'),
    path('profile/<str:username>/', ProfileView.as_view(), name='profile'),
    path('profile/<str:username>/update/',
         ProfileUpdateView.as_view(), name='profile_update'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
]

books/urls.py
from django.urls import path
from books.views import IndexView, BookAddView, MyBookView, BookUpdateView, BookDeleteView
from books.views import SearchView

app_name = 'books'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('search/', SearchView.as_view(), name='search'),
    path('add_book', BookAddView.as_view(), name='add_book'),
    path('my_books', MyBookView.as_view(), name='my_books'),
    path('my_books/<int:pk>/update', BookUpdateView.as_view(), name='update_book'),
    path('my_books/<int:pk>/delete', BookDeleteView.as_view(), name='delete_book'),
]

good_reads/urls.py
from django.contrib import admin
from django.urls import path, include

# for serving static file during development
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('books.urls'))
]

# Only if debug mode is false, means in productions
if settings.DEBUG == False:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

# Serving media files during development
if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser

# Create your models here.


class Account(AbstractUser):
    '''
    User model in Django model contains username, first_name, last_name, email, password, groups,
    user_permissions, is_staff, is_active, is_superuser, last_login, date_joined
    '''
    is_author = models.BooleanField(default=False)
    picture = models.ImageField(
        upload_to='user_photos/', default='accounts/images/default-profile.png')

    def __str__(self):
        return f"{self.last_name}, {self.first_name}"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from accounts.models import Account


class JoinForm(UserCreationForm):
    ''' password1 and password2 are created within UserCreationForm class, needed to override to 
    add placeholder for display. 
    Note that only password is saved in model and password1 and password2 are used for validation of
    password only.
    '''
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={'autocomplete': 'new-password', 'placeholder': 'Enter Password'}),
        strip=False,
    )
    password2 = forms.CharField(
        label=("Password confirmation"),
        widget=forms.PasswordInput(
            attrs={'autocomplete': 'new-password', 'placeholder': 'Enter Password again'}),
        strip=False,
    )

    class Meta:
        model = Account
        fields = ['first_name', 'last_name',
                  'username', 'password1', 'password2', 'is_author', 'picture', ]
        exclude = []
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'Enter First Name', 'autofocus': 'autofocus'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Enter Last Name'}),
            'username': forms.TextInput(attrs={'placeholder': 'Enter Username'}),
        }

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView, ListView, DetailView, UpdateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.forms import JoinForm
from accounts.models import Account


class UserLoginView(LoginView):
    template_name = 'accounts/login.html'


class UserLogoutView(LogoutView):
    # Redirected directly to login page once logged out
    next_page = reverse_lazy('accounts:login')


class JoinView(FormView):
    template_name = 'accounts/signup.html'
    form_class = JoinForm
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        '''
        The function will validate form against the model(look for max_length, data type) and
        save it in the table.
        '''
        form.save()
        return super().form_valid(form)


class AuthorsView(ListView):
    model = Account
    template_name = 'accounts/authors.html'

    def get_queryset(self):
        # only getting the users where author flag is set to True
        return Account.objects.filter(is_author=True)


class ProfileView(LoginRequiredMixin, DetailView):
    model = Account
    template_name = 'accounts/profile.html'
    '''
    DetailView will pick the pk from Url path and try to find the corresponding pk in model Account,
    Once found the object will be passed to template as 'object'
    '''
    # DetailView looks for pk or slug| Changed to look for username using get_object method

    def get_object(self):
        '''
        Used self.request.user.username in place of self.kwargs.get("username") to get
        the current logged in user all the time. So if user wants to access someone's else
        profile, user will always get his/her profile. 
        '''
        # print(self.request.user.username)
        # print(self.kwargs.get('username'))
        return Account.objects.get(username=self.request.user.username)


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'accounts/signup.html'
    model = Account
    form_class = JoinForm

    # by default the updateview looks for pk or slug to get current_object| passing username to url dispather
    def get_object(self):
        return Account.objects.get(username=self.kwargs.get("username"))

    # get_success_url needs to be added to pass username as kwargs to url dispather
    def get_success_url(self):
        return reverse_lazy('accounts:profile', kwargs={'username': self.kwargs.get('username')})

accounts/templates/accounts/authors.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!--Content-->
<div class="grid-container">
    <!-- CSS Grid Container -->
    {% for author in account_list %}
    <div class="grid-item">
        <img src="{{ author.picture.url }}" alt="author_image">
        <h3>{{ author.first_name }} {{ author.last_name }}</h3>
        <h4>Member since: {{ author.date_joined|date:'F d, Y' }}</h4>
        <p>Genre: Romance, Historical Fiction, Science Fiction</p>
    </div>
    {% endfor %}
</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Login Section -->
<form method="POST">
    <div class="signup_div login_div">
        <h2 id="text_center">Login</h2>
        <hr>
        {% csrf_token %}
        {{ form.as_p }}

        <div class="clearfix">
            <button type="button" class="cancelbtn">Cancel</button>
            <button type="submit" class="submitbtn">Sign In</button>
        </div>
    </div>
</form>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content%}
<div class="profile">

    <div class="item">
        <img id='profile_img' src="{{ object.picture.url }}" alt="user_image">
    </div>

    <div class="item">
        <h3>Name: {{ object.get_full_name }} </h3>

        <h4>Username: {{ object.get_username }} </h4>
        <h4>Member Since: {{ object.date_joined|date:'F d, Y' }}</h4>
        <h4>Author: {% if object.is_author %} Yes {% else %} No {% endif %}</h4>
        <h4>Last Login: {{ object.last_login|date:'F d, Y' }}</h4>
        <h4>Books: </h4>

        <br>
        <button style="width: 50%; margin-left: 50px;" type="submit">
            <a href="{% url 'accounts:profile_update' object.get_username %}">Update</a>
        </button>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Sign Up Section -->
<form method="POST" enctype="multipart/form-data">
    <div class="signup_div">
        {% if user.is_authenticated %}
        <h2 id="text_center">Update Account</h2>
        {% else %}
        <h2 id="text_center">Create Account</h2>
        {% endif %}
        <p>Please fill in this form to create an account.</p>
        <hr>
        {% csrf_token %}

        {% for field in form %}
        {{ field.label_tag }}
        {{  field }}
        {% endfor %}

        <!--
            This shows an error on form validation
            {{ form.errors }}
        -->

        <div class="clearfix">
            <button type="button" class="cancelbtn">Cancel</button>
            {% if user.is_authenticated %}
            <button type="submit" class="submitbtn">Update</button>
            {% else %}
            <button type="submit" class="submitbtn">Create</button>
            {% endif %}
        </div>
    </div>
</form>
{% endblock content %}