accounts/urls.py
from django.urls import path
from accounts.views import JoinView, AuthorsView, UserLoginView, UserLogoutView, ProfileView, ProfileUpdateView

from django.views.generic import RedirectView
# RedirectView will redirect url--> www.google.com/accounts/ to www.google.com/accounts/login/

app_name = 'accounts'
urlpatterns = [
    path('', RedirectView.as_view(url='login/', permanent=True)),
    path('join/', JoinView.as_view(), name='join'),
    path('authors/', AuthorsView.as_view(), name='authors'),
    path('profile/<str:username>/', ProfileView.as_view(), name='profile'),
    path('profile/<str:username>/update/',
         ProfileUpdateView.as_view(), name='profile_update'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
]

books/urls.py
from django.urls import path
from books.views import IndexView, BookAddView, MyBookView, BookUpdateView, BookDeleteView
from books.views import SearchView

app_name = 'books'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('search/', SearchView.as_view(), name='search'),
    path('add_book', BookAddView.as_view(), name='add_book'),
    path('my_books', MyBookView.as_view(), name='my_books'),
    path('my_books/<int:pk>/update', BookUpdateView.as_view(), name='update_book'),
    path('my_books/<int:pk>/delete', BookDeleteView.as_view(), name='delete_book'),
]

good_reads/urls.py
from django.contrib import admin
from django.urls import path, include

# for serving static file during development
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('books.urls'))
]

# Only if debug mode is false, means in productions
if settings.DEBUG == False:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

# Serving media files during development
if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'books/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/css/signup.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/css/login.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/css/profile.css' %}">
    <link rel="icon" href="{% static 'books/logo/logo.webp' %}" type="image/icon type">
    <title>GoodREADS</title>
    {% block link %}{% endblock link %}
</head>

<body>
    <main>
        <header>
            <!--Navbar-->
            <h1>Good<span>READS</span></h1>
            <nav>
                <ul>
                    <li><a {% if '/' == request.path %} class="active_link" {% endif %}
                            href="{% url 'books:index' %}">Home</a></li>
                    {% if user.is_authenticated %}
                    <li><a {% if 'my_books' in request.path %} class="active_link" {% endif %}
                            href="{% url 'books:my_books' %}">My Books</a></li>
                    {% endif %}
                    <li><a {% if 'authors/' in request.path %} class="active_link" {% endif %}
                            href="{% url 'accounts:authors' %}">Authors</a></li>
                    <li><a href="{% url 'books:search' %}">Search</a></li>

                    {% if user.is_authenticated %}
                    <li><a {% if 'profile/' in request.path %} class="active_link" {% endif %}
                            href="{% url 'accounts:profile' user.username %}">Profile</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                    {% else %}
                    <li><a {% if 'login/' in request.path %} class="active_link" {% endif %}
                            href="{% url 'accounts:login' %}">Log In</a></li>
                    <li><a {% if 'join/' in request.path %} class="active_link" {% endif %}
                            href="{% url 'accounts:join' %}">Join</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>

        {% block content %}
        {% endblock content %}

    </main>
    <!--Footer-->
    <footer>
        <p>&copy; 2020 Alpha. All rights reserved.</p>
    </footer>
</body>

</html>