books/urls.py
from django.urls import path
from books.views import IndexView, BookAddView, MyBookView, BookUpdateView, BookDeleteView
from books.views import SearchView

app_name = 'books'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('search/', SearchView.as_view(), name='search'),
    path('add_book', BookAddView.as_view(), name='add_book'),
    path('my_books', MyBookView.as_view(), name='my_books'),
    path('my_books/<int:pk>/update', BookUpdateView.as_view(), name='update_book'),
    path('my_books/<int:pk>/delete', BookDeleteView.as_view(), name='delete_book'),
]

good_reads/urls.py
from django.contrib import admin
from django.urls import path, include

# for serving static file during development
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('books.urls'))
]

# Only if debug mode is false, means in productions
if settings.DEBUG == False:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

# Serving media files during development
if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.utils.timezone import now

from accounts.models import Account


class Genre(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Book(models.Model):
    '''
    author added as foreign key, if author is deleted, field here in book would be set to NULL
    By default,
        genre is added as many to many field relation, a single book can have more than 1 genres
        there will be only one copy of a book available
        date_added set to today for new instance
        ratings shall be displayed upto 2 decimal places & only 3 maximum digits. Largest value: 9.99
        short description will be of 100 character length
    '''
    title = models.CharField(max_length=100)
    genre = models.ManyToManyField(Genre)
    author = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    copies = models.IntegerField(default=1)
    date_added = models.DateField(default=now)
    ratings = models.DecimalField(max_digits=3, decimal_places=2, default=0.0)
    short_desc = models.TextField(max_length=200)
    description = models.TextField(max_length=500)
    cover_picture = models.ImageField(upload_to='book_photos/')

    def __str__(self):
        return self.title

    def display_genre(self):
        '''
        In case there are more than one genre per book, all the available genres for a book are
        joined with comma and space.
        '''
        return ', '.join(item.name for item in self.genre.all())

books/forms.py
from django import forms
from books.models import Book
from accounts.models import Account
from django.forms import ModelForm


class BookForm(ModelForm):
    # author = forms.ModelMultipleChoiceField(queryset = Account.objects.filter(is_author=True))
    # author = forms.ChoiceField(choices=[(author.id, author) for author in Account.objects.filter(is_author=True)])

    class Meta:
        model = Book
        fields = ('title', 'genre', 'author', 'short_desc',
                  'description', 'ratings', 'cover_picture', 'copies', 'date_added')
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Enter Title', 'autofocus': 'autofocus'}),
        }

books/views.py
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, UpdateView, DeleteView

from books.forms import BookForm
from books.models import Book

from django.views.generic.edit import FormMixin
class IndexView(ListView):
    # Main index page view
    template_name = 'books/index.html'
    model = Book
    ordering = ['-id']
    # Pagination
    paginate_by = 8

    def get(self, request):
        # Calling rent_book function to sort out calculation of renting book
        if(request.GET.get('book_Id')):
            rent_book(request.GET.get('book_Id'))
        return super().get(request)

class BookAddView(CreateView):
    template_name = 'books/add_book.html'
    form_class = BookForm
    success_url = reverse_lazy('books:index')


class MyBookView(ListView):
    model = Book
    template_name = 'books/my_books.html'
    '''
    Filters out the books for the current logged user
    '''

    def get_queryset(self):
        queryset = Book.objects.filter(author=self.request.user)
        return queryset

    def get(self, request, *agrs, **kwargs):
        '''
        Get to check if queryset is empty- 
        Yes: Redirect to add_book url 
        No: Display my_books
        '''
        self.object_list = self.get_queryset()
        if not self.object_list:
            # Redirect to add_book when querySet is empty| Meaning when no data
            return redirect('books:add_book')
        context = self.get_context_data()
        return self.render_to_response(context)


class BookUpdateView(UpdateView):
    model = Book
    template_name = 'books/add_book.html'
    form_class = BookForm
    success_url = reverse_lazy('books:my_books')


class BookDeleteView(DeleteView):
    model = Book
    success_url = reverse_lazy('books:my_books')

    # Get request method is changed to use post directly skipping the _confirm_delete template
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

class SearchView(TemplateView):
    template_name = 'books/search_book.html'

    def get(self, request):
        if request.GET.get('book'):
            search_book = request.GET.get('book')
            search_data={
                'book_list': Book.objects.filter(title__contains=search_book),
            }
            return render(request, template_name='books/search_book.html', context=search_data)
        # when the page is loaded first time|TemplateView class to handle get request
        return super().get(request)


def rent_book(book_id):
    book=Book.objects.get(id=book_id)
    if book.copies>=1:
        book.copies-=1 # book is rented
    else:
        # what happens when book.copies goes to zero| Should not be available for rent. 
        # add a message that book can't be rented
        pass
    book.save()

books/templates/books/_display_book.html
<div class="grid-container">
    <!-- CSS Grid Container -->
    {% for book in book_list %}
    <div class="grid-item">
        <h4>{{ book.display_genre }}</h4>
        <img src="{{ book.cover_picture.url }}" alt="{{ book.title }}">
        <h4>{{ book.title }}</h4>
        <h5>by {{ book.author.get_full_name }}</h5>
        <p>Rating: {{ book.ratings }}</p>
        <p>{{ book.short_desc }}</p>
        <form method="GET">
            <input type="hidden" name="book_Id" value="{{ book.id }}">
            <input type="submit" value="Rent Book">
        </form>
    </div>
    {% endfor %}
</div>

books/templates/books/add_book.html
{% extends 'base.html' %}

{% load static %}
{% block link %}
<link rel="stylesheet" href="{% static 'books/css/add_book.css' %}">
{% endblock link %}

{% block content %}

<h2> Add Book Details</h2>
<form method="POST" enctype="multipart/form-data">
    <div class="add_book">
        {% csrf_token %}
        {{ form.as_ul }}

        <div class="clearfix" id='button_book'>
            {% if form.title %}
            <button type="submit" class="submitbtn">Update Book</button>
            {% else %}
            <button type="submit" class="submitbtn">Add Book</button>
            {% endif %}
        </div>
    </div>
</form>
{% endblock content %}

books/templates/books/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!--Content-->
{% include 'books/_display_book.html' %}

<!--Pagination-->
{% if is_paginated %}
{% if page_obj.has_previous %}
<button>
    <a href="?page={{ page_obj.previous_page_number }}">Previous Page</a>
</button>
{% elif page_obj.has_next %}
<button>
    <a href="?page={{ page_obj.next_page_number }}">Next Page</a>
</button>
{% else %}
<span></span>
{% endif %}
</ul>
{% endif %}

{% endblock content %}

books/templates/books/my_books.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
<link rel="stylesheet" href="{% static 'books/css/my_books.css' %}">
{% endblock link %}
{% block content %}

<!-- When user has any book added -->
<div class="grid-container">
    <!-- CSS Grid Container -->
    {% for book in book_list %}
    <div class="grid-item">
        <h4>{{ book.display_genre }}</h4>
        <img src="{{ book.cover_picture.url }}" alt="{{ book.title }}">
        <h4>{{ book.title }}</h4>
        <h5>by {{ book.author.get_full_name }}</h5>
        <p>Rating: {{ book.ratings }}</p>
        <p>{{ book.short_desc }}</p>
        <button>
            <a href="{% url 'books:update_book' book.id %}">Edit</a>
        </button>

        <form method="POST" action="{% url 'books:delete_book' book.id %}">
            {% csrf_token %}
            <button type="submit">
                <a href="{% url 'books:delete_book' book.id %}">Delete</a>
            </button>
        </form>
    </div>
    {% endfor %}
    <div class="grid-item">
        <button>
            <a href="{% url 'books:add_book' %}">Add Book</a>
        </button>
    </div>
</div>

{% endblock content %}

books/templates/books/search_book.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
<link rel="stylesheet" href="{% static 'books/css/add_book.css' %}">
{% endblock link %}
{% block content %}

<h2> Search Book</h2>
<form method="GET">
    <div class="add_book">
        <label>Search books(by Title/Author)</label>
        <input type='text' placeholder="Search book" name="book" required>

        <div class="clearfix" id='button_book'>
            <button type="submit" class="submitbtn">Search</button>
        </div>
    </div>
</form>

<br>
{% include 'books/_display_book.html' %}

{% endblock content %}